export { default as IconAlertCircle } from "../../public/icons/alert_circle.svg?react";
export { default as IconArrowRight } from "../../public/icons/arrow_right.svg?react";
export { default as IconCheck } from "../../public/icons/check.svg?react";
export { default as IconChevronDown } from "../../public/icons/chevron_down.svg?react";
export { default as IconClose } from "../../public/icons/close.svg?react";
export { default as IconDot } from "../../public/icons/dot.svg?react";
export { default as IconFilter } from "../../public/icons/filter.svg?react";
export { default as IconUK } from "../../public/icons/flags/uk.svg?react";
export { default as IconUSA } from "../../public/icons/flags/usa.svg?react";
export { default as IconHeartHandshake } from "../../public/icons/heart_handshake.svg?react";
export { default as IconInfoCircle } from "../../public/icons/info_circle.svg?react";
export { default as Logo } from "../../public/icons/logo.svg?react";
export { default as IconMenu } from "../../public/icons/menu.svg?react";
export { default as IconMoneySearch } from "../../public/icons/money_search.svg?react";
export { default as IconAmericaExpress } from "../../public/icons/payment/american_express.svg?react";
export { default as IconMasterCard } from "../../public/icons/payment/master_card.svg?react";
export { default as IconPayPal } from "../../public/icons/payment/paypal.svg?react";
export { default as IconVisa } from "../../public/icons/payment/visa.svg?react";
export { default as IconPin } from "../../public/icons/pin.svg?react";
export { default as IconRapid } from "../../public/icons/rapid.svg?react";
export { default as IconSearch } from "../../public/icons/search.svg?react";
export { default as IconFacebook } from "../../public/icons/socials/facebook.svg?react";
export { default as IconInstagram } from "../../public/icons/socials/instagram.svg?react";
export { default as IconLinkedIn } from "../../public/icons/socials/linkedIn.svg?react";
export { default as IconTwitter } from "../../public/icons/socials/twitter.svg?react";
export { default as IconYoutube } from "../../public/icons/socials/youtube.svg?react";

export { IconStar } from "./IconStar";
